spring.application.name=lnpsystem
spring.output.ansi.enabled=ALWAYS

# H2 configuration
spring.datasource.url=jdbc:h2:mem:bancxdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Hibernate is disabled because Liquibase wil manage scheme
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.json

# OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Logging
#logging.structured.format.console=ecs
#logging.structured.format.file=ecs
#logging.level.root=debug
#logging.level.org.springframework.web=debug
#logging.level.org.hibernate=error
